### ISSUE TITLE
Script to delete samples from DB

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/SAMADhi#9]
We need a script to delete samples from the database, maybe with a protection allowing only the user to delete its own sample.

Fairly easy to do, I just open this issue to remember to do it sometime :smile:

**Comment by delaere** [comment]
A script may be prepared, but the idea was to use the web interface for such cases, to avoid mistakes. Is there a use case that requires automation of the deletion?

**Comment by blinkseb** [comment]
Ah right, forgot about the web interface! If it's doable here, no need for a script.
